@startuml
' Model de Domini

class TaskManager {
}

class Usuari {
    nom: String
}

class Task{
    title: string
    desc: string
    dataInici: Date
    dataFinal: Date
}

TaskManager "1" -- "1..*" Usuari : enters >
TaskManager "1" -- "1..*" Task : storage >

@enduml